config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]
  root "galleries#index"

  resources :users, only: [:new, :create, :index, :show]
  resources :galleries do
    resources :images, only: [:show, :new, :create, :edit, :update]
  end

  resources :tags, only: [:index, :create, :show]

  resources :images, only: [] do
    resources :comments, only: [:create]
    resource :like, only: [:create, :destroy]
  end

  resources :groups, only: [:index , :new, :create, :show] do
    resources :group_memberships, only: [:create, :destroy]
  end
end

#  get "/" => "galleries#index"
 # get "/galleries/new" => "galleries#new"
 # post "/galleries" => "galleries#create"
 # get "/galleries/:id" => "galleries#show"
 # get "/galleries/:id/edit" => "galleries#edit"
 # patch "/galleries/:id" => "galleries#update"
 # delete "/galleries/:id" => "galleries#destroy"

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :images
  belongs_to :user

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
    render :index
  end

  def new
    @gallery = current_user.galleries.new
    render :new
  end

  def show
    @gallery = load_gallery_from_url
  end

  def edit
    @gallery = load_personal_gallery_from_url
  end

  def update
   @gallery = load_personal_gallery_from_url

    if @gallery.update(gallery_params)
      redirect_to gallery_path(@gallery)
    else
      render :edit
    end
  end

  def destroy
    gallery = load_personal_gallery_from_url
    gallery.destroy

    redirect_to "/"
  end

  def create
    @gallery = current_user.galleries.new(gallery_params)

  if @gallery.save
    redirect_to gallery_path(@gallery)
  else
    render :new
  end
  end

  private
  def gallery_params
    params.require(:gallery).permit(:name, :description)
  end

  def load_gallery_from_url
    Gallery.find(params[:id])
  end

  def load_personal_gallery_from_url
    current_user.galleries.find(params[:id])
  end
end

app/views/galleries/_form.html.erb
<%= render "error_messages", target: gallery %>

<%= form_for gallery do |form| %>
  <div>
  <%= form.label :name %>
  <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <%= form.submit %>
  <% end %>

app/views/galleries/edit.html.erb
<h2> Editing gallery <%= @gallery.name %> </h2>


<%= render "form", gallery: @gallery %>

app/views/galleries/index.html.erb
<h1> Elizabeth says hi </h1>

<%= link_to "Make a New Gallery", new_gallery_path %>
<ul>
  <% @galleries.each do |gallery| %>
    <li>
      <%= link_to gallery.name, gallery %>
      -
      <%= gallery.description %>

      <%= link_to "Edit", edit_gallery_path(gallery) %>

      <%= form_for gallery, method: :delete do |form| %>
        <%= form.submit "Delete" %>
      <% end %>
    </li>
  <%end%>
</ul>

app/views/galleries/new.html.erb
<h2> Create a New Gallery</h2>

<%= render "form", gallery: @gallery %>

app/views/galleries/show.html.erb
<%= link_to "Add new image" ,new_gallery_image_path(@gallery)%>
<h2> This is a page for <%= @gallery.name %> </h2>
<p><%= @gallery.description %></p>

<ul>
  <% @gallery.images.each do |image| %>
    <li>
    <%= image_tag image.url %>
    <%= link_to image.name, gallery_image_path(@gallery, image) %>
    </li>
  <% end %>
</ul>